import 'package:flutter_football_core/entities/country.enum.dart';

const leagueSeedData = [
  {
    'name': 'english 1',
    'country': Country.england,
    'tier': 1,
  },
  {
    'name': 'english 2',
    'country': Country.england,
    'tier': 2,
  },
  {
    'name': 'english 3',
    'country': Country.england,
    'tier': 3,
  },
  {
    'name': 'english 4',
    'country': Country.england,
    'tier': 4,
  },
];

const clubSeedData = {
  'english 1': [
    {'name': 'Ashford United'},
    {'name': 'Blackheath FC'},
    {'name': 'Chelmsbrook City'},
    {'name': 'Duxbury Athletic'},
    {'name': 'Eastwick Rangers'},
    {'name': 'Farnworth Town'},
    {'name': 'Grantley FC'},
    {'name': 'Harlington Rovers'},
    {'name': 'Ironbridge City'},
    {'name': 'Kingsbridge FC'},
    {'name': 'Ludworth United'},
    {'name': 'Marlbrook City'},
    {'name': 'Northbury FC'},
    {'name': 'Oxbridge Athletic'},
    {'name': 'Pembroke Wanderers'},
    {'name': 'Queensmere FC'},
    {'name': 'Rothbury United'},
    {'name': 'Southmark City'},
    {'name': 'Thornbury FC'},
    {'name': 'Westbrook Athletic'},
  ],
  'english 2': [
    {'name': 'Aldridge Town'},
    {'name': 'Burnsworth FC'},
    {'name': 'Crestwood United'},
    {'name': 'Dartford City'},
    {'name': 'Enfield Athletic'},
    {'name': 'Fairbrook Rovers'},
    {'name': 'Grimsworth FC'},
    {'name': 'Halewood United'},
    {'name': 'Ivybridge City'},
    {'name': 'Kenilworth FC'},
    {'name': 'Loxley Rangers'},
    {'name': 'Millbrook Town'},
    {'name': 'Norbury Athletic'},
    {'name': 'Oldcastle FC'},
    {'name': 'Prestwick United'},
    {'name': 'Radcliffe City'},
    {'name': 'Stockbridge FC'},
    {'name': 'Trentham United'},
    {'name': 'Uxbridge City'},
    {'name': 'Wembley Athletic'},
    {'name': 'Yarmouth Town'},
    {'name': 'Bridgewood FC'},
    {'name': 'Chesterfield Rovers'},
    {'name': 'Dunwich United'},
  ],
  'english 3': [
    {'name': 'Abbeydale FC'},
    {'name': 'Barrowfield United'},
    {'name': 'Coventry Athletic'},
    {'name': 'Doncaster City'},
    {'name': 'Elmbridge Rovers'},
    {'name': 'Fleetwood Town'},
    {'name': 'Guildford City'},
    {'name': 'Hampstead United'},
    {'name': 'Islington FC'},
    {'name': 'Kensington Athletic'},
    {'name': 'Lancaster City'},
    {'name': 'Maidstone Rovers'},
    {'name': 'Newark Town'},
    {'name': 'Oakwood United'},
    {'name': 'Peterborough FC'},
    {'name': 'Redbridge City'},
    {'name': 'Shrewsbury Athletic'},
    {'name': 'Tamworth United'},
    {'name': 'Wakefield FC'},
    {'name': 'Yeovil City'},
    {'name': 'Bromley Rovers'},
    {'name': 'Crawley United'},
    {'name': 'Dartmouth FC'},
    {'name': 'Exeter City'},
  ],
  'english 4': [
    {'name': 'Aldershot Town'},
    {'name': 'Basildon United'},
    {'name': 'Chesham City'},
    {'name': 'Dorchester FC'},
    {'name': 'Eastleigh Rovers'},
    {'name': 'Frome Athletic'},
    {'name': 'Gloucester United'},
    {'name': 'Hastings City'},
    {'name': 'Ipswich Athletic'},
    {'name': 'Kidderminster FC'},
    {'name': 'Leatherhead Town'},
    {'name': 'Maidenhead City'},
    {'name': 'Nuneaton Rovers'},
    {'name': 'Orpington United'},
    {'name': 'Poole City'},
    {'name': 'Ramsgate FC'},
    {'name': 'Salisbury United'},
    {'name': 'Torquay City'},
    {'name': 'Weymouth FC'},
    {'name': 'Worthing United'},
    {'name': 'Banbury City'},
    {'name': 'Chippenham Rovers'},
    {'name': 'Daventry Town'},
    {'name': 'Evesham Athletic'},
  ],
};
